name: crawler

on:
  workflow_dispatch: {}

jobs:
  crawler:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          package-manager-cache: false # Disable automatic npm caching if not required
      - name: install dependencies
        run: npm ci
      - name: Create .env file
        run: |
          rm -f .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
      - name: Fetch gp data
        run: npm run hydrate
